root = true

[*]
indent_style = space
indent_size = 4
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
end_of_line = lf
bracket_spacing = true
max_line_length = 120

[*.ts]
quote_type = single

# Indentation override for all ymls
[*.yml]
indent_style = space
indent_size = 2
