message: "chore: update RELEASE-NOTES [skip ci]"
split: true
out: ./notes
ignored-labels:
  - in-release-note
  - released
assets:
  - CHANGELOG.md
  - package.json
decoration:
  type/feature: '## :zap: '
  type/bug: '## :bug: '
