debug: true
dryRun: false

plugins:
    - '@semantic-release/commit-analyzer'
    - '@semantic-release/changelog'
    #- '@semantic-release/npm'
    - '@semantic-release/github'

branches:
    - main
