debug: true
dryRun: false

plugins:
    - '@semantic-release/commit-analyzer'
    - '@semantic-release/release-notes-generator'
    - '@semantic-release/npm'
    - '@semantic-release/changelog'
    - [
          '@semantic-release/git',
          assets: ['package.json', 'RELEASE-NOTES.md']
          message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      ]
    - '@semantic-release/github'

branches:
    - main
