message: "chore: update RELEASE-NOTES [skip ci]"
split: true
out: '.'
labels:
  include:
    - release-note/use
  ignore:
    - release-note/published
  end:
    - release-note/published
assets:
  - CHANGELOG.md
  - package.json
decoration:
  type/feature: '## :zap: '
  type/bug: '## :bug: '
