name: Preview Release Notes in PR

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Release notes preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - run: npm run preview -- ${{ github.event.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
