name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - run: npm run rng
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}

